name: qrsigned
description: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  path: ^1.9.0
  flutter:
    sdk: flutter
  encrypt: ^5.0.1
  mongo_dart: ^0.10.0
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.0
  overlay_support: ^2.1.0
  socket_io_client: ^2.0.3+1
  audioplayers: ^6.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg
    - assets/notificacion.mp3

flutter_launcher_icons:
  android: false
  ios: false
  windows:
    generate: true
  image_path: "assets/logo.jpg"
